services:
  voice_ros2:
    container_name: voice_ros2
    image: voice_ros2
    runtime: nvidia
    environment:
      ROS_DOMAIN_ID: 42
      DISPLAY: $DISPLAY
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,video,utility,graphics
      QT_X11_NO_MITSHM: '1'
      ALSA_CARD: 'Generic' # use aplay -l to find the card name
    network_mode: host
    ipc: host
    privileged: true
    stdin_open: true
    tty: true
    devices:
      - /dev/snd:/dev/snd
    command: 
      - bash
      - -c
      - |
          python3 /scripts/voice_cloning.py "Hey Buddy, how are you?" &
          ros2 launch voice_ros2 voice_ros2.launch.py